channels:
  - conda-forge
dependencies:
  - appmode
  - anndata==0.7.6
  - bokeh==2.4.2
  - jupyter-bokeh==3.0.2
  - jupyter-contrib-nbextensions==0.5.1
  - jupyter-nbextensions-configurator==0.5.0
  - jupyterlab-widgets==1.1.0
  - numpy==1.21.2
  - pandas==1.3.2
  - Pillow==9.0.1
  - widgetsnbextension==3.6.0
